object Versions {

    const val gradlePlugin = "4.2.1"
    const val kotlin = "1.5.0"
    const val timber = "4.7.1"
    const val appCompat = "1.3.0"
    const val material = "1.3.0"
    const val constraintLayout = "1.1.3"
    const val androidxAnnotations = "1.2.0"
    const val androidxLegacySupport = "1.0.0"
    const val archLifecycleVersion = "2.3.1"
    const val recyclerViewVersion = "1.2.1"
    const val cardViewVersion = "1.0.0"
    const val gsonVersion = "2.8.8"
    const val fragmentKtxVersion = "1.3.6"
    const val ktxCore = "1.6.0"
    const val jUnit = "4.12"
    const val androidxTestVersion = "1.1.0"
    const val pagingVersion = "3.1.0"
    const val shimmer = "0.5.0"
    const val lifeCycle = "2.3.1"
    const val navVersion = "2.3.5"
    const val intuit = "1.0.6"
    const val easyPermissions = "1.0.0"
    const val datastore = "1.0.0"
    const val retrofit2Version = "2.9.0"
    const val retrofitInterceptor = "4.9.1"
    const val coroutinesCoreVersion = "1.5.2"
    const val coroutinesAndroidVersion = "1.3.9"
    const val coroutinesPlayService = "1.1.1"
    const val hiltVersion = "2.38.1"
    const val hiltNavGraph = "1.0.0"
    const val hiltLifeCycleVersion = "1.0.0"
    const val ankoVersion = "0.10.8"
    const val glideVersion = "4.12.0"
    const val glideCompilerVersion = "4.11.0"
    const val roomVersion = "2.4.0-alpha03"
    const val mockito = "2.8.47"
    const val mockitoCore = "2.8.47"
    const val espresso  ="3.0.1"
    const val testRunner ="1.0.1"

}